### ISSUE TITLE
Fast-LCD-I2C does not work! Examples does not run.

### ISSUE THREAD

**Issue by Ted-Printable** [KStandiford/Fast-LCD-I2C#1]
Hi, I am using a portable IDE 1.8.19 and was looking forward to using this library.

I tried to run the Hello World example since my own code produced a strange error (strange to me).

My original issue was that using interrups with an LCD that obviously uses "Wire.h", doesnt work. I am not a program wiz but seems there are inteference with the interups used by wire.

Would be great to use your "Fast-LCD-I2C" if it works, but will be even greater if you could help with my interrupt problem.
Many thanks!!

Below is the error generated with Hello World Example.:

Arduino: 1.8.19 (Windows 10), Board: "Arduino Uno"

In file included from C:\Users\Andries\Documents\..arduino-1.8.19\libraries\LCD_I2Cfast\LCD_I2C.cpp:18:0:

C:\Users\Andries\Documents\..arduino-1.8.19\libraries\LCD_I2Cfast\LCD_I2C.h: In function 'void sleep_ms(uint32_t)':

C:\Users\Andries\Documents\..arduino-1.8.19\libraries\LCD_I2Cfast\LCD_I2C.h:23:38: error: 'delay' was not declared in this scope

 inline void sleep_ms(uint32_t time) {delay(time);}

                                      ^~~~~

C:\Users\Andries\Documents\..arduino-1.8.19\libraries\LCD_I2Cfast\LCD_I2C.h: In function 'void sleep_us(uint64_t)':

C:\Users\Andries\Documents\..arduino-1.8.19\libraries\LCD_I2Cfast\LCD_I2C.h:24:38: error: 'delayMicroseconds' was not declared in this scope

 inline void sleep_us(uint64_t time) {delayMicroseconds(time);}

                                      ^~~~~~~~~~~~~~~~~

exit status 1

Error compiling for board Arduino Uno.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by KStandiford** [comment]
Well that's embarrassing...
It turns out that the Pi Pico board environment includes some things that the Arduino environments did not. I have fixed it so that the code at least compiles for real Arduino boards. Please try to run it again for me! Thanks, by the way, for such a complete report.

**Comment by Ted-Printable** [comment]
Hi, according to my very blond daughter, all human beings are allowed one blond moment per day. LoL.
Not embarrassing, just human.
Thanks, it works great. Love the Demo2004, shows everything I can use all in one place.
Great stuff!!
Any advice on using interrupts with LCD. I am trying to run a simple hall effect sensor on interrupt pin so not to miss any event, but seems LCD always uses wire, which uses interrupts, which clash  with my hall sensor pin.

Would be a shame to use a more expensive display on such simple project as a counter.
Any ideas or advice will be appreciated.
Many thanks.

**Comment by KStandiford** [comment]
Closing the issue per @Ted-Printable confirmation of fix.

**Comment by KStandiford** [comment]
Whew! Glad it's working and really glad you like it! Please consider leaving a review and maybe even a star on github to help others find it in their search..
As to interrupts, now I am laughing! Using interrupts with a Hall sensor is literally the next thing I was going to do after I read my e-mail yesterday! (But in Pi-Pico land, not Arduino!). 
I'm not really an Arduino expert, but a review of the interrupt stuff looks fairly straightforward. Is your code posted somewhere I could see it? You could just create a repository on github and upload it. Or have you asked the question already on a forum somewhere?
One thought occurs to me about a possible pitfall. You should NOT print to the LCD from inside the interrupt handler routine for the pin interrupt. I see that several of the examples published on the web do this. It is VERY bad practice. Debounce the switch or sensor if necessary, save the timing if you are building a rev counter or increment number of pulses or whatever in the interrupt handler and then periodically output the results from the loop function. (like -- while(1) {delay(xxx);setcursor();print(whatever);})
    On Saturday, July 9, 2022 at 02:28:11 AM PDT, Ted-Printable ***@***.***> wrote:  
 
 


Hi, according to my very blond daughter, all human beings are allowed one blond moment per day. LoL.
Not embarrassing, just human.
Thanks, it works great. Love the Demo2004, shows everything I can use all in one place.
Great stuff!!
Any advice on using interrupts with LCD. I am trying to run a simple hall effect sensor on interrupt pin so not to miss any event, but seems LCD always uses wire, which uses interrupts, which clash with my hall sensor pin.

Would be a shame to use a more expensive display on such simple project as a counter.
Any ideas or advice will be appreciated.
Many thanks.

**Comment by KStandiford** [comment]
Also, did you find tis article? attachInterrupt() - Arduino Reference

| 
| 
|  | 
attachInterrupt() - Arduino Reference

The Arduino programming language Reference, organized into Functions, Variable and Constant, and Structure keywo...
 |

 |

 |




    On Saturday, July 9, 2022 at 06:40:35 AM PDT, Keith Standiford ***@***.***> wrote:  
 
  Whew! Glad it's working and really glad you like it! Please consider leaving a review and maybe even a star on github to help others find it in their search..
As to interrupts, now I am laughing! Using interrupts with a Hall sensor is literally the next thing I was going to do after I read my e-mail yesterday! (But in Pi-Pico land, not Arduino!). 
I'm not really an Arduino expert, but a review of the interrupt stuff looks fairly straightforward. Is your code posted somewhere I could see it? You could just create a repository on github and upload it. Or have you asked the question already on a forum somewhere?
One thought occurs to me about a possible pitfall. You should NOT print to the LCD from inside the interrupt handler routine for the pin interrupt. I see that several of the examples published on the web do this. It is VERY bad practice. Debounce the switch or sensor if necessary, save the timing if you are building a rev counter or increment number of pulses or whatever in the interrupt handler and then periodically output the results from the loop function. (like -- while(1) {delay(xxx);setcursor();print(whatever);})
    On Saturday, July 9, 2022 at 02:28:11 AM PDT, Ted-Printable ***@***.***> wrote:  
 
 


Hi, according to my very blond daughter, all human beings are allowed one blond moment per day. LoL.
Not embarrassing, just human.
Thanks, it works great. Love the Demo2004, shows everything I can use all in one place.
Great stuff!!
Any advice on using interrupts with LCD. I am trying to run a simple hall effect sensor on interrupt pin so not to miss any event, but seems LCD always uses wire, which uses interrupts, which clash with my hall sensor pin.

Would be a shame to use a more expensive display on such simple project as a counter.
Any ideas or advice will be appreciated.
Many thanks.

**Comment by KStandiford** [comment]
OK, this hack of Hello World works on my Pi Pico. Your pin numbers will vary. Your mileage may as well ;-).



#include <Wire.h>
#include <LCD_I2C.h>


// we have a 20char, 4 line display at address 027 hex
#define MAX_LINES 4
#define MAX_CHARS 20
#define LCD_ADDRESS 0x27
#define Hall_Pin 14
#define LED_Pin 25

// The I2C bus speed. 100000 is the default, but if your display supports it,
// You can try 400000 for faster response. (Though your eye won't notice.)
#define WIRESPEED 100000

// Declare and initialize the LCD object

LCD_I2C lcd = LCD_I2C(LCD_ADDRESS, MAX_CHARS, MAX_LINES);


void setup()
{

  delay(2000);  // give the user a chance to focus ... (optional)

  // Set the I2C bus speed. This is optional, but if you want to change the
  // default speed of 100000, here is where to do it!

  Wire.setClock(WIRESPEED);

  // Initialize the display. This also initializes the I2C bus.

  lcd.begin();

  // Display is initialized to cleared, backlight on and cursor at 0,0 (upper left edge).
  // Note that all the print methods work, but the print line will not. You must 
  // reposition the cursor yourself. See below...

  lcd.print("Hello Arduino");   // Say hello!

  // Demonstrate cursor positioning.

  lcd.setCursor(3,1);      // line 1 is second line, 3 is fourth character

  // Finish the classic message with a call to writeString, rather than print.
  // In practice, this is usually substantially faster than print.

  lcd.writeString("World! (20x4)");     // Finish the classic message!

  // Now set the input pin for the hall sensor with pull up & LED pin

  pinMode(Hall_Pin, INPUT_PULLUP);
  pinMode(LED_Pin, OUTPUT);
  attachInterrupt(digitalPinToInterrupt(Hall_Pin),HallISR,CHANGE);

}
int Hall = 1;

void loop()
{
  while(1){
    delay(100); // wait half a second
    lcd.setCursor(5,2);
    if(Hall)
      lcd.writeString("High");
     else
      lcd.writeString("Low ");
    
  }
}

void HallISR()
{
    Hall = digitalRead(Hall_Pin);
    digitalWrite(LED_Pin,Hall);
}

**Comment by Ted-Printable** [comment]
Hi Keith. I am sorry, haven’t had time to properly look at your e-mail below, will do so tomorrow, when I can focos.I did want to send you my code as requested. Did not do it at first as I “presume” this is a universal problem. Seems it simply is not possible to use interrupts while using a a display using the “Wire.h” library.Only reason I asked the question is because I am not accustomed to giving up. However, my knowledge and programming skills are all but professional or advanced, so I contemplate that it could be possible, if someone with better skills look at it. The below code work 100% when you remove the LCD stuff in it. The RPM measurement is fairly good also, I suspect limited by hardware and real world limitations. (Millis is not a RTC., and such.)At the moment I am looking at a SPI display to try and see if I can get past this problem, but since I never used SPI before, it is messy. (Sorry, this script below still has the old Library in it for LCD.) /*  This is a Uno connected to 20x4 LCD with I2C. *  Added Hall effect sensor UH8104_UTC to  *  Digital INTERUPT pin 2.   *   *  Works 100% if LCD disabled. *  THIS DOES NOT WORK FULLY WITH LCD, SENSOR UNRESPONSIVE WITH LCD. *  WIRE USES INTERRUPTS FOR LCD POSSIBLY CONFLICTS WITH *  HALL EFFECT INTERRUPT. */ #include <Wire.h> #include <LiquidCrystal_I2C.h>  // Connect to LCD via I2C, default address 0x27 (A0-A2 not jumpered)  LiquidCrystal_I2C lcd = LiquidCrystal_I2C(0x27, 20, 4); // Change to (0x27,16,2) for 16x2 LCD const byte intPin = 2;            // Digital INTERRUPT Pin of the Hall sensor.volatile bool Detectstate = LOW;  // Byte (0-255) to store detection state in Interrupt function.float rpm = 0.0;                  // For reading rpm.unsigned long Cycles = 0;         // Number of rotations counted.unsigned long nowTime = 0;        // Time reading at detection.unsigned long lastTime = 0;       // Previous Time magnet was detected. // Pre Program Setup.void setup() {  pinMode(intPin, INPUT_PULLUP);  // Following line calls function when Magnet was detected on intPin and signal is falling away.  attachInterrupt(digitalPinToInterrupt(intPin), magnetDetector, FALLING);    Serial.begin(115200);           // Begin Serial Monitor at 115200 B/Sec Board rate.  while(!Serial);                 // Wait for serial to be running.  Serial.println("Serial is working:");  Serial.println();   lcd.begin(20, 4);                       // Defining 20 columns and 4 rows of lcd display  lcd.init();                             // Initiate the LCD      lcd.backlight();                        // To Power ON the back light  lcd.clear();                            // Clear Screen      delay(1000);      // lcd.rightToLeft();               // Change display direction from default.  lcd.print("LCD-Screen Working!");       // Print to Screen (data,BASE) Base=2,10,8,16  //  delay(1000);                        // Show print for 1 seconds.  //  lcd.clear();                        // Clear LCD and set cursur to home.  //  lcd.home();                         // Sets cursor to Upper Left Corner.} // End Setup. // Program begins.void loop() {  if (Detectstate == HIGH) {                             // Detect magnet has pased.      Cycles++;                                          // When magnet passed, count as a cycle.      Detectstate = LOW;                                 // Restet detection flag.      nowTime = millis();      lastTime = nowTime - lastTime;                     // Calculate period passed since last detection.      rpm = (1.0 / lastTime) * 60000.0;                      // Calculate RPM from period.      lastTime = nowTime;                                // Reset timer for period calucation.       Serial.print("Cycle = ");      Serial.print(Cycles);      Serial.print("    Speed = ");      Serial.print(rpm);      Serial.println(" RPM ");        lcd.setCursor(0,2);      lcd.print("Cycle = ");      lcd.print(Cycles);      lcd.setCursor(0,3);      lcd.print("Speed = ");      lcd.print(rpm,1);      lcd.print(" RPM ");   } // End if.      } // End loop. void magnetDetector() {  Detectstate = HIGH;} // End function magnetDetector. From: Keith StandifordSent: Saturday, 09 July 2022 16:50To: KStandiford/Fast-LCD-I2CCc: Ted-Printable; MentionSubject: Re: [KStandiford/Fast-LCD-I2C] Fast-LCD-I2C does not work! Examples does not run. (Issue #1) OK, this hack of Hello World works on my Pi Pico. Your pin numbers will vary. Your mileage may as well ;-).#include <Wire.h>#include <LCD_I2C.h>// we have a 20char, 4 line display at address 027 hex#define MAX_LINES 4#define MAX_CHARS 20#define LCD_ADDRESS 0x27#define Hall_Pin 14#define LED_Pin 25// The I2C bus speed. 100000 is the default, but if your display supports it,// You can try 400000 for faster response. (Though your eye won't notice.)#define WIRESPEED 100000// Declare and initialize the LCD objectLCD_I2C lcd = LCD_I2C(LCD_ADDRESS, MAX_CHARS, MAX_LINES);void setup(){delay(2000); // give the user a chance to focus ... (optional)// Set the I2C bus speed. This is optional, but if you want to change the// default speed of 100000, here is where to do it!Wire.setClock(WIRESPEED);// Initialize the display. This also initializes the I2C bus.lcd.begin();// Display is initialized to cleared, backlight on and cursor at 0,0 (upper left edge).// Note that all the print methods work, but the print line will not. You must// reposition the cursor yourself. See below...lcd.print("Hello Arduino"); // Say hello!// Demonstrate cursor positioning.lcd.setCursor(3,1); // line 1 is second line, 3 is fourth character// Finish the classic message with a call to writeString, rather than print.// In practice, this is usually substantially faster than print.lcd.writeString("World! (20x4)"); // Finish the classic message!// Now set the input pin for the hall sensor with pull up & LED pinpinMode(Hall_Pin, INPUT_PULLUP);pinMode(LED_Pin, OUTPUT);attachInterrupt(digitalPinToInterrupt(Hall_Pin),HallISR,CHANGE);}int Hall = 1;void loop(){while(1){delay(100); // wait half a secondlcd.setCursor(5,2);if(Hall)lcd.writeString("High");elselcd.writeString("Low ");}}void HallISR(){Hall = digitalRead(Hall_Pin);digitalWrite(LED_Pin,Hall);}—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by KStandiford** [comment]
Wow, that got mangled somehow. But it looks like your interrupt code is flawless. I don't think you have an interrupt problem. I think this is a timing problem. Once the LCD code is running, your main loop takes so long to execute that you start missing pulses. Your code already assumes that cycles does not overflow. So let's count cycles in the interrupt handler and time stamp the last one. Then in the main loop we look to see if it changed. If so, use the change and the saved time stamp to get the period as before.

    // add global variables
    volatile unsigned long detectTime = 0;
    unsigned long lastTime = 0;
    volatile unsigned long cycles= 0;
    unsigned long oldCycles = 0;
    
    //in loop() to start the loop...
    if(cycles != oldCycles) {                       // Something happened!
    nointerrupts();               //MUST turn interrupts off to read both values without any possible update in the middle!
    long nowTime = detectTime;            // Sample the last magnet detect time
    long nowCycles = cycles;                 //Sample the last cycle counter
    interrupts();                                      // Turn them back on
    counts = nowCycles- oldCycles;     // Count change
    oldCycles = nowCycles;                  // update old counter
    float period = (float) (nowTime - oldTime)/(float) counts;  // Time Change / number of counts = period
    oldTime = nowTime;                      // and reset the last sample time
    // ..and given the period, compute the rest...
    
    // and the magnet detector
    void magnetDetector() { 
        cycles++;                     //bump the cycle counter
        detectTime = millis();  // and record when we got it. NOTE: millis doesn't run in interrupt handlers,
                                           // so we get exactly what it was when the interrupt occurred!
    }

**Comment by Ted-Printable** [comment]
Hi Keith.
Sorry about the scrambled message, I replied directly by e-mail, that came out a mess on Github. Please be patient with me, I don't do facebook, I don't tweet and until recently, I did not Github, so the old dog is still learning.

In my test I simulated events bringing a magnet to the sensor a couple of times. I never contemplated the possibility the loop takes too long to process, or that the interrupts may cause disruptions. My hat off to you sir.

In your loop you turn the interrupts off and then on again, I follow your logic with this, I think to make sure this critical part is not disrupted. 
I can however happily report that using your Fast_LCD_I2C library solved the problem in my original script, with no other changes. I ran Wire at 400 000 as suggested.  (PS: Had to double my delay after lcd.clear() to 2 seconds, otherwise garbage remains and the screen does not properly clear.)

With other words, your Fast_LCD_I2C is a true winner in speed and performance, in my book at least.

I tried your code also, works with and without the interrupts being turned off and on. I suspect cause my testing is slow. The "noInterupts()" will probably give more stable results at speed, becoming essential then.

I added the final code below just for refrence.
Many thanks for your assistance.

`/*  This is a Uno connected to 20x4 LCD
 *  Wotks on 5V and I2C connection
 *  Added Hall effect sensor UH8104_UTC to 
 *  Digital INTERUPT pin 2. 
*/

#include <Wire.h> 

// Use Fast LCD, copy files to library.
// Connect to LCD via I2C, default address 0x27 (A0-A2 not jumpered)
// Change to (0x27,16,2) for 16x2 LCD
#include <LCD_I2C.h>             
LCD_I2C lcd = LCD_I2C(0x27, 20, 4); 

// Global variables
const byte intPin = 2;            // Digital INTERRUPT Pin of the Hall sensor.
float rpm = 0.0;                  // For reading rpm.
unsigned long Cycles = 0;         // Number of rotations counted.
unsigned long oldCycles = 0;      // Previous count. 
unsigned long nowCycles = 0;      // Current count. 
unsigned long detectTime = 0;     // Time reading at detection.
unsigned long oldTime = 0;        // Previous Time of cycle.
unsigned long nowTime = 0;        // Current Time of cycle.

// Pre Program Setup.
void setup() {
  // Set the I2C bus speed. This is optional, but if you want to change the
  // default speed of 100000, here is where to do it!
  Wire.setClock(400000);
  
  pinMode(intPin, INPUT_PULLUP);
  // Following line calls function when Magnet was detected on intPin and signal is falling away.
  attachInterrupt(digitalPinToInterrupt(intPin), magnetDetector, FALLING);
  
  Serial.begin(115200);           // Begin Serial Monitor at 115200 B/Sec Board rate.
  while(!Serial);                 // Wait for serial to be running.
  Serial.println("Serial is working:");
  Serial.println();

  lcd.begin();                            // Defining 20 columns and 4 rows of lcd display
  lcd.backlight();                        // To Power ON the back light
  lcd.clear();                            // Clear Screen
    delay(2000);                          // Show print for 1 seconds.
  lcd.print("LCD-Screen Working!");       // Print to Screen (data,BASE) Base=2,10,8,16
  lcd.setCursor(0,2);
  lcd.writeString("Cycles = 0");          // writestring is faster than print.
  lcd.setCursor(0,3);
  lcd.writeString(" Speed = 0");          // writestring is faster than print.
} // End Setup.

// Program begins.
void loop() {
  if(Cycles != oldCycles) {                // Something happened!
     //noInterrupts();                       // MUST turn interrupts off to read both values without any possible update in the middle!
       nowTime = detectTime;               // Sample the last magnet detect time
       nowCycles = Cycles;                 // Sample the last cycle counter
     //interrupts();                         // Turn them back on
    
     float Counts = nowCycles - oldCycles; // Count change
     oldCycles = nowCycles;                // update old counter
     float period = (float) (nowTime - oldTime)/(float) Counts;  // Time Change / number of counts = period
     oldTime = nowTime;                   // and reset the last sample time.
     rpm = (1 / period) * 60000.0;
     
      Serial.print("Cycle = ");
      Serial.print(Cycles);
      Serial.print("    Speed = ");
      Serial.print(rpm);
      Serial.println(" RPM"); 

      lcd.setCursor(9,2);
      lcd.print(Cycles);
      lcd.setCursor(9,3);
      lcd.print(rpm,0);
  } // End if.
} // End loop.

// Function to detect Magnet.
void magnetDetector() { 
    Cycles++;                     // bump the cycle counter
    detectTime = millis();        // and record when we got it.
} // End function magnetDetect.      NOTE: millis doesn't run in interrupt handlers,`

**Comment by KStandiford** [comment]
This stuff will stave off dementia WAY better than Facebook or Twitter, though I may have an apoplectic stroke from frustration at some point. I too have been drinking from the fire hose learning these new systems! But “take yes for an answer”! Congratulations! And thanks for all the fish! (The complements. My wife says I will be insufferable for a week.)

The key to interrupts is to become paranoid about the fact they can occur between any two instructions in your program. This leads to two rules for interrupt and non-interrupt code:

1. They should never modify the same variable.
2. Interrupt code cannot pass back more than one variable.

Rule 2 can be broken using special data structures. Both can be broken by carefully preventing interrupts while sampling or checking and modifying data. 

So interrupts should be off while “reading” `Cycles` and `detectTime` In order to make sure the interrupt code doesn’t change them after one is read but before the other is sampled. 

Optimizing compilers like to keep needed variables lying around in registers which can create another vulnerability between the if statement and the saving of `Cycles`.  (And other places possibly).  So `Cycles` and `detectTime` should be declared `volatile`. (Check this in your code.)

Both these things are so unlikely that you would probably never notice the glitch. But we also used to say “With a 1MHz computer, a one in a million chance takes about a second! “ But it’s a bear to find when you really care…

Finally, the last optimization (totally not needed of course is to use `sprintf()` to format your numbers because print outputs some formats one character at a time. If you are a masochist, read my `Theory of operation` to understand why. 

Again, thanks for finding that I never tried compiling for a real Arduino board. Glad things are working!
